### ISSUE TITLE
Controller、Service、Repository、Domain の命名について

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#11]
https://github.com/sunakan/realworld-kotlin-springboot-jdbc/blob/main/docs/architecture.png

アーキテクチャ構成を見ると、意図せずしてDDDに寄せてきているので、**package 名** を変更した方がいいかもしれません。

|旧 package 名|新 package 名|
|-|-|
|Controller|Presentation|
|Service|UseCase|
|Repository|Infra|
|Domain|Domain（変更なし）|

その他の検討事項
- **クラス名**の変更
- セパレートインタフェースの導入
- 1 UseCase 1 public メソッド

**Comment by sunakan** [comment]
【前提】軽量DDD周りっぽいことは好みなので、ガンガン以下は実践してました

- オニオンアーキテクチャっぽいのは意識してる（一番したいのは大切なロジックとそれ以外（腐敗防止部分）で極力分けたい）
- 値オブジェクトガンガン導入

**Comment by sunakan** [comment]
### クラス名の変更

👌 

### 1 UseCase：1public メソッド

テストファイルが小さくなるので好み（もともと〇〇Handlerとしてやっていた）

👌 

### セパレートインターフェースの導入

自分自身の書き方としてDIしそうなインターフェースとその実装を同一ファイルに書きがちなので、避けてました 🙇 

入れたいです？

**Comment by sunakan** [comment]
あ、プレゼン層にある、Controllerはそのままが良いです？（粒度含め）

**Comment by sunakan** [comment]
UserRegisterHandler.ktというように、1URL：1ファイルとして切りそうになったので

**Comment by sunakan** [comment]
|package 名|メインクラス名|
|-|-|
|presentation|HogeController|
|usecase|FugaUseCase|
|infra|FooRepositoryImpl|
|domain|FooRepository(Interface)|

**Comment by sunakan** [comment]
セパレートインターフェース導入

**Comment by sunakan** [comment]
@Msksgm 
このissue解決で良さそうと思うので、一旦閉じます


もし同じことで決めたいことがあればreopenしていきましょう
