### ISSUE TITLE
お気に入りにする（favorite）のDBテスト失敗する

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#118]
## branch

- main

## 内容

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/183231093-5dc2cbdf-68db-48e6-989d-4f45695aa2da.png">

## 対応PR

- https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/120

**Comment by sunakan** [comment]
これ対応します

**Comment by Msksgm** [comment]
承知しました
