### ISSUE TITLE
request package の場所について

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#13]
request package って presentation package 配下に置くべきですかね？

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/tree/fafdb5f8b23275d89774845b616686a79defc358/src/main/kotlin/com/example/realworldkotlinspringbootjdbc/request

**Comment by sunakan** [comment]
【前提】
- presentationがWebの入り口と出口を担っている気がしております
- Controllerが入り口、出口を担っている
- 層が今の所、presentation/usecase/infra/domainの4層である

前提より、出口専用のDTOをresponseパッケージとして、presentation層においてます

なので入り口専用（と考えている）DTOをrequestパッケージとして、presentation層に置きました

どこに置くほうが more betterとかってありますかね。。。？

**Comment by sunakan** [comment]
あああああああ、間違えました

**Comment by sunakan** [comment]
requestが外に出てました orz

**Comment by Msksgm** [comment]
質問の仕方が悪かったですね、request が外に出ている理由が気になりました。
前提には完全に同意です 👍

**Comment by sunakan** [comment]
おっしゃるとおり、requestはpresentation層の中にあるべきだと思ってます

（てっきりpresentation層にあるものだという前提でコメント書いてました）

**Comment by sunakan** [comment]
位置変更しました

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/commit/cdd2ae7be2e293ca47cdff04511ca99ffc94c874

**Comment by sunakan** [comment]
@Msksgm 
もし確認したら、Closeお願いします 🙇

**Comment by Msksgm** [comment]
確認したのでクローズします。
