### ISSUE TITLE
newWithoutValidation の引数をプリミティブにするか、オブジェクトにするか

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#15]
考慮漏れしていたんですが、newWithoutValidation の引数がプリミティブ型のものが残っているので、コンフリクトする前に早いタイミングで、オブジェクトに統一します？

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/blob/3d854f2c5c9890f2a8feee75cf23be87c3d9388a/src/main/kotlin/com/example/realworldkotlinspringbootjdbc/domain/RegisteredUser.kt#L45-L57

**Comment by sunakan** [comment]
Slackに書いた

> “バリデーションがある時“、そのプロパティ1個1個を全て値オブジェクトとして出すべきか悩んだ話

> ユーザーネームみたいな上のやつみたいな値オブジェクトの存在を知らなくてもいいのではないか

につながるのですが、代表的なオブジェクトの存在だけ知っている方がより良いのではないか？

とか思ったんですが、どう思います？


ただまぁ、ここまで書きましたが、一度極端に寄せることで見える世界もあると信じて、全部オブジェクト型に統一してしまいましょうか

**Comment by Msksgm** [comment]
> につながるのですが、代表的なオブジェクトの存在だけ知っている方がより良いのではないか？
> とか思ったんですが、どう思います？

うーん、「１つのプロパティしか持たない値オブジェクト」を他の値オブジェクト（or エンティティ）が知っている状態になるので、個人的にはやはり反対ですね。。。
あと、引数にString型が複数個並んでいるときに、ファクトリがコンパイルエラーを出せないのも避けたいという点でも、やはり全部オブジェクト型に寄せたいです。

**Comment by sunakan** [comment]
はーい

全然OKです
