### ISSUE TITLE
post /articles/{slug}/comments （Comment 登録）の際に、UseCase の戻り値は Comment か RegisteredComment か

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#16]
`post /articles/{slug}/comments` したときに、リクエストボディは以下で、

```json
{
  "comments": {
    "body": "hoge-body"
  }
}
```

レスポンスは以下

```json
{
  "comments": {
    "id": 1,
    "body": "hoge-body",
    "createdAt": "....",
    "updatedAt": "....",
    "author": "hoge-author-name",
  }
}
```

なんですけど、RegisterdComment ドメインオブジェクトを作るべきか、Response package 側でなんとかするか迷っています。
Comment オブジェクトの author は Profile オブジェクトなので、ドメイン的には異なりますが、レスポンスのためだけに、ドメインオブジェクトを持たせるのか微妙なラインになっています。 
Comment オブジェクトを プレゼンテーション層 に戻した時の問題点は、`"author"` を取得する際に、`comment.profile.username.value` という、デメテルの法則に反していそうになることです。

**Comment by sunakan** [comment]
前置き１：6月24日で割と考え方が極端に変わった可能性がある
  - （1番大事なのは抽象化されたデータ構造・モデルの形で、UIではない、そして振る舞いでもない（だからといって適当で良いかと言われれば違う）。。。相当引っ張られていたと反省＆モデリングについてオブジェクトが振る舞いを持つという考え方から外れそう）
 
前置き２：しかし、以下はもともとそうだっと思う

前提：基本的に「データの詰め替え」はPresentation層にしたい
  - （層は可能なら減らしたい。（もちろん必要なら用意するが、説明責任も負う））さよならCleanArchitecture）


答え

```
 そして「データの詰替え」は、データ構造を全部知っていても構いません

それがデメテルの法則に反しているか？と聞かれた時、もしかしたらそうは思ってないのかもです
（蛇足2にも書きましたが、最小って誰にとっての？ってのが変わるからです）
```

以下蛇足です

多分ですが、現在の自分の考えは「デメテルの法則（最小知識の法則）」に関して、適切なデータ構造を守ることができれば、それが `最` 小化はあまり気にしておらず、デメテルの法則違反上等かもしれません
（知り過ぎか？ファットじゃないか？構造おかしくないか？みたいなことはもちろん考え続けますが）


別の表現というか別アプローチになりますが、蛇足2

最後にお客さんが見るUI（データ構造）が「デメテルの法則で言う `最小` の知識である」というわけでは `ない` みたいな感じでしょうか、、、

**Comment by Msksgm** [comment]
# Answer

詰め替えのタイミングではデータ構造全てを知っていても良い

一旦、クローズ。
同じような議論をするときには、他のイシューを立てて、引用にする
