### ISSUE TITLE
CommentId と UserId の値オブジェクトについて

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#20]
CommentId と UserId は外部から入力されるパラメータの1つですが、数字以外が入力されたときはどうしますか？
request package に NullableCommentId クラスを用意して、数字以外（文字列や複合）の場合はnullを返すか、CommentId や UserId のバリデーションでエラーを出すようにしますか？

**Comment by sunakan** [comment]
## CommentIdに対して

`DELETE /articles/{slug}/comments/{id}`

なので、CommentIdはバリデーションしましょう

NullableCommentIdはrequestとして不要な気がしますがいかがでしょう？

```kt
@deleteMapping(.../{comment-id})
fun delete(@pathparameter(comment-id) commentId: String?) {}
```

とかにするのはいかがでしょう？

## UserIdに対して

これって外部から指定して入力されましたっけ？

**Comment by Msksgm** [comment]
承知しました。UserId は自分の勘違いです。すみません

**Comment by Msksgm** [comment]
CommentIdってユースケース層に受け取るとき（パスパラメータなので {comment-id}）には String 型で valueとして持つのは Int の方がいいとかありますかね？
具体的には、

```kotlin
interface CommentId {
    val value: String
}
```

にすると、RealWorld で定義されているCommentId のレスポンスはダブルクォーテーションで囲まれていないので、Int 変換が必要になります（詳しくは https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/17 にて）。
これも、**ドメインオブジェクトの他の部分はDTO for View Modelとたまたま一致したけど、ここは一致しなかったから詰め替えるときに変換が必要**みたいな認識で問題ないですかね？

**Comment by sunakan** [comment]
> CommentIdってユースケース層に受け取るとき（パスパラメータなので {comment-id}）には String 型で valueとして持つのは Int の方がいいとかありますかね？

これはIntに変換してもらうことは可能でしょうか？（ValueObject　With　Validationのとき、Intへの変換を試みる）

理由としては、ID類はとりあえず統一したほうがわかりやすいかなーとか思ったからです（好みの問題で、IDの型で、UUIDが混ざった途端破綻はするのですが。。）

UserIdなども全て

**Comment by sunakan** [comment]
あー、、、それでrequestパッケージ側にNullableCommentIdがあってもいいのでは？ということなんですね。。すいません、完全に考慮不足でした

すいません、、NullableCommentIdでもあってもいい気がしてきました。。

それか Int?で引数を受け取った場合、 `@deleteMapping(.../{comment-id})` で `/hoge` などが着た時、nullで受け取れるなら `Int?` でもいいかもです。。

**Comment by Msksgm** [comment]
> それか Int?で引数を受け取った場合、 @deleteMapping(.../{comment-id}) で /hoge などが着た時、nullで受け取れるなら Int? でもいいかもです。。

`@PathVariable` でキャストできない変数がきても、null にはならず、400エラーが戻ってくる。
なので、NullableCommentId を用意する。

**Comment by Msksgm** [comment]
こちらのPRがマージされたら、クローズします。

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/pull/17

**Comment by Msksgm** [comment]
マージされたため、クローズします。
