### ISSUE TITLE
調査：ORM

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#201]
## 概要

[Java ORマッパー選定のポイント #jsug](https://www.slideshare.net/masatoshitada7/java-or-jsug)

今

- Spring JDBC【JDBCラッパー型】

最初のフィルタ

|id|name|型|候補？|🙅‍♂️理由|
|:---|:---|:---|:---:|:---|
|1|Exposed|？|||
|2|JOOQ|クエリビルダー型|||
|3|Spring Data JDBC|？|||
|4|Spring Data REST|？|🙅‍♂️|シンプルすぎる予感|
|5|Spring Data JPA|ORマッパー型|🙅‍♂️|JPA怖い|
|6|MyBatis|SQLマッパー型|🙅‍♂️|XMLが嫌|
|7|Hibernate|ORマッパー型|🙅‍♂️|JPA怖い|
|8|Doma|SQLマッパー型|🙅‍♂️|迷う。。|
|9|Komapper|？||良さげ？|
|10|Ktorm|？||？|

### JDBCラッパー型

- 使いやすい
- 学習コストが低い

### SQLマッパー型

- SQLは別途テキストファイルに書くことが多い

### クエリビルダー型

- SQLタイプミスの心配がない

### ORマッパー型

- 学習コスト高い

**Comment by sunakan** [comment]
## Spring Data JDBC

- `@Query` で複数のテーブルに対してREADはできそう
- CrudRepositoryは実装しなくて済みそうで楽そう
- Redisを導入する時、Spring Data Redisとかで使えるかも？（未調査）

## 参考

どっちも良かった

- [Spring Bootキャンプ：Spring Boot + Spring Data JDBC編](https://stackoverflow.com/questions/64255511/spring-data-jdbc-save-to-two-tables)
- [Spring Data JDBC save to two tables](https://stackoverflow.com/questions/64255511/spring-data-jdbc-save-to-two-tables)

**Comment by sunakan** [comment]
## JOOQ

- Entityの自動生成は良さそう

**Comment by sunakan** [comment]
## Exposed


## 参考

[[Kotlin] ExposedとKomapperの違い](https://zenn.dev/nakamura_to/articles/af0cd8a0cbe355)

**Comment by sunakan** [comment]
## Komapper

- 良さげ
- 日本語のドキュメントがあるの良い

**Comment by sunakan** [comment]
Entityの自動生成があるJOOQが今の所採用候補

### 理由

ドメイン層にDB用のアノテーションをつけたくない（いわゆるORM用のEntityにしたくない）

そうなると、Entity用クラスを別で作る必要がある。これはだるそう

それを自動生成できるのが JOOQ だという理解をしている

**Comment by sunakan** [comment]
エンティティを自分で作るなら

- Komapper
- Spring Data JDBC

の2択感

**Comment by sunakan** [comment]
## Ktorm

よさげ感

**Comment by sunakan** [comment]
JOOQでやってみる

**Comment by sunakan** [comment]
あ、oracleとかの商用だとつらい。。かな。。。？

**Comment by sunakan** [comment]
[Spring Data JDBC Codegen Tool](https://github.com/kalyanmulampaka/spring-data-jdbc-codegen)

とかあったが、古すぎる

**Comment by sunakan** [comment]
[Kotlinでデータベースアクセス「Komapper」](https://tech.isid.co.jp/entry/2021/12/14/database_access_in_kotlin_using_komapper)

> Komapperのクエリは分解できます。先ほどの例で示したクエリを3つの部品に分解して書いてみます。

ElixirのEcto感あって良さげ

**Comment by sunakan** [comment]
JOOQ外すなら、Spring Data JDBC or Komapperだろうか・・

Ktormは調べてないけど、それ使うならKomapperかなぁ

**Comment by sunakan** [comment]
一旦保留

**Comment by sunakan** [comment]
JOOQだと、自動生成にDB接続が必要っぽい
- H2だけなら大丈夫そう（[jOOQのコード生成をデータベース接続無しで行う](https://zenn.dev/kentama/articles/0170ad25a2b83a9ab20e)）

DB不要なテストでもコンパイル時には必要ということで、微妙な点も見えた

Komapper検討したくなってきた

**Comment by Msksgm** [comment]
ちょっと使いやすい JDBC という意味では、JDBI も選択肢にあがるのかもしれません

http://jdbi.org/

**Comment by Msksgm** [comment]
Spring Data JDBC については以下を参照

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/issues/278

**Comment by sunakan** [comment]
- Spring Data JDBC
- JDBI
- Komapper

を試してみたい

で終わります
