### ISSUE TITLE
デフォルトとして未実装を表現するTODO()をthrow NotImplementedErrorに変更

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#211]
## 概要

- interfaceの初期実装として、 `TODO()` を使っている
- しかし、interfaceの初期実装として、一生TODOの状態を期待している場合がほぼで、TODOというわけではない
- TODOは対応するべき箇所につけていきたい

KotlinにはNotImplementedErrorというのがあった

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-not-implemented-error/

TODO関数は throw NotImplementedError をしているだけっぽい

**Comment by Msksgm** [comment]
## TODO を使っている箇所

- XXXUseCase.execute 
- XXXRepository のメソッド
- Unexpected エラー（途中で方針が変わったため）
- Either で絶対に失敗しない場合の Left 型
- ユースケース（ユーザー観点的な意味で）において絶対に使わない箇所
- Controller の　`TODO: serializeUnexpectedErrorForResponseBodyをやめる`
- 未記入のテスト
- 後回しにした実装

## 分類

- `throw NotImplementedError` に置換
  - XXXUseCase.execute 
  - XXXRepository のメソッド
- 削除
  - Unexpected エラー（途中で方針が変わったため）
  - ユースケース（ユーザー観点的な意味で）において絶対に使わない箇所（要検討？）
- 実装する
  - Controller の　`TODO: serializeUnexpectedErrorForResponseBodyをやめる`
  - 未記入のテスト
  - 後回しにした実装
- Unexpected Error を実装する？
  - Either で絶対に失敗しない場合の Left 型

**Comment by sunakan** [comment]
TODOできになったら別でopenします
