### ISSUE TITLE
API テストでレスポンスボディを厳密に比較したい

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#214]
## 概要

API テストを実施した際に、ContentResultMatchers.json はデフォルトだと「類似している」ことのみを比較する（[json](https://spring.pleiades.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/servlet/result/ContentResultMatchers.html#json-java.lang.String-boolean- )）。
その場合、以下の問題点が発生する。

- 期待値に存在しない key-value が存在してもテストが通過する

ContentResultMatchers.json の第２引数（strict）に`true`を指定することで、厳密な比較が可能になるが、createdAt、updatedAt といったメタデータは実行時に依存されるので、全てに適用ができない。
これらの問題点を解決する。

**Comment by Msksgm** [comment]
## 方針

レスポンスボディに対して 2 つの方針でおこないたい。

- メタデータが含まれない場合 -> strict = true にする
- メタデータが含まれる場合 -> jackson を使用して、レスポンスをオブジェクトに変換して比較する

### 2 つにわけた理由

後者の方法で統一しても、全てのパターンのレスポンスを詰め替えるのはコストが高いと考えたため。エラーメッセージはレスポンスが固定なので、問題ないと考えた。

**Comment by sunakan** [comment]
もしかしたらマッチャ側でなんとかできるかもです

利用するのは `JsSONAssert` (assertJの中で使われてそう？)

[JavaでJSONを比較する（特定の項目を無視するやり方）](https://nainaistar.hatenablog.com/entry/2020/06/15/Java%E3%81%A7Json%E3%82%92%E6%AF%94%E8%BC%83%E3%81%99%E3%82%8B%EF%BC%88%E7%89%B9%E5%AE%9A%E3%81%AE%E9%A0%85%E7%9B%AE%E3%82%92%E7%84%A1%E8%A6%96%E3%81%99%E3%82%8B%E3%82%84%E3%82%8A%E6%96%B9%EF%BC%89)


```java
@Test
void test_01() throws JSONException {
    // language=json
    String expect = "{ \"time\" : {\n" +
            "  \"insertTime\": 201912010023,\n" +
            "  \"updateTime\": 202008111234\n" +
            "}," +
            "\"animal\": \"gorilla\"}\n";

    // language=json
    String actual = "{ \"time\" : {\n" +
            "  \"insertTime\": 201912010023,\n" +
            "  \"updateTime\": 999999999999\n" +
            "}," +
            "\"animal\": \"gorilla\"}\n";


    JSONAssert.assertEquals(expect, actual,
            new CustomComparator(JSONCompareMode.STRICT,
                    new Customization("time.insertTime", (o1, o2) -> true), // ここでcreated_atを指定したら良さそう
                    new Customization("time.updateTime", (o1, o2) -> true)
            )
    );
}
```

**Comment by Msksgm** [comment]
> もしかしたらマッチャ側でなんとかできるかもです
> 
> 利用するのは `JsSONAssert` (assertJの中で使われてそう？)
> 
> [JavaでJSONを比較する（特定の項目を無視するやり方）](https://nainaistar.hatenablog.com/entry/2020/06/15/Java%E3%81%A7Json%E3%82%92%E6%AF%94%E8%BC%83%E3%81%99%E3%82%8B%EF%BC%88%E7%89%B9%E5%AE%9A%E3%81%AE%E9%A0%85%E7%9B%AE%E3%82%92%E7%84%A1%E8%A6%96%E3%81%99%E3%82%8B%E3%82%84%E3%82%8A%E6%96%B9%EF%BC%89)
> 
> ```java
> @Test
> void test_01() throws JSONException {
>     // language=json
>     String expect = "{ \"time\" : {\n" +
>             "  \"insertTime\": 201912010023,\n" +
>             "  \"updateTime\": 202008111234\n" +
>             "}," +
>             "\"animal\": \"gorilla\"}\n";
> 
>     // language=json
>     String actual = "{ \"time\" : {\n" +
>             "  \"insertTime\": 201912010023,\n" +
>             "  \"updateTime\": 999999999999\n" +
>             "}," +
>             "\"animal\": \"gorilla\"}\n";
> 
> 
>     JSONAssert.assertEquals(expect, actual,
>             new CustomComparator(JSONCompareMode.STRICT,
>                     new Customization("time.insertTime", (o1, o2) -> true), // ここでcreated_atを指定したら良さそう
>                     new Customization("time.updateTime", (o1, o2) -> true)
>             )
>     );
> }
> ```

これでうまくいきそうだったので、これでやります〜
