### ISSUE TITLE
get /profiles/{username} でログイン時と非ログイン時の挙動について

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#25]
## 概要

get /profiles/{username} を叩いたときに、ヘッダーを確認して、ログイン状態なのかそうじゃないのかを確認したほうが良い気がしますね。

- 非ログイン状態 -> Profile の follow が false 固定
- ログイン状態 -> Profile の follow が true or false

**Comment by sunakan** [comment]
たしかーに！

というか前回モデリングしてたときは以下のような感じでしたね。。

```kt
sealed interface Relation {
    data class Unknown(user: User) : Relation
    data class Unfollowed(user: User) : Relation
    data class Followed(user: User) : Relation
}
```

**Comment by Msksgm** [comment]
TODOとしては以下が追加されます。

- [ ] `/profile/{username}` は全て、Authorization の確認。get のみ追加でOK
- [ ] XXXProfileUseCase には、引数に `currentUserId`  type of `UserId`（or `currentUser` type of `RegisteredUser` ） が必要だった

どうでしょうか？

**Comment by sunakan** [comment]
> /profile/{username} は全て Authorization の確認

OK

> 1つめはgetのみの修正が必要です

Yes

> (GET修正の文脈で)おそらくUseCaseが増える？（AuthorizedShowProfileUseCaseとUnauthorizedShowProfileUseCase）

これは迷いますよねー（いい感じの分岐点だと思います）

- UseCase自体をテストしやすいのは2つ作ることかと思います
  - そうすると、UseCaseを2つDIしないといけなくなって、Controllerのテストが辛くもなりそうです。。

（Showを今ぱっと実装しろと言われて）自分でしたら 引数を Option<RegisteredUser> を1つ追加して` UseCase は1つのまま`で行くかもしれません。。

（理由書いてましたが、、長文になったり、うまく言葉にできなかったので、消しました 🙇 ）

> 2つめはUseCaseに引数を追加する必要があります

Yes, OKです

**Comment by Msksgm** [comment]
> （Showを今ぱっと実装しろと言われて）自分でしたら 引数を Option<RegisteredUser> を1つ追加して UseCase は1つのままで行くかもしれません。。

了解です、自分もその案を考えていました。よく考えたら、1エンドポイント1UseCase の原則を崩してしまうので、そっちの方向性に寄せたいと思います。
- null -> 絶対falseを返す
- RegisteredUser -> DB を確認して false or true を返す

> (フォロー・アンフォローは RegisteredUser を引数に取る認識です)

承知しました

**Comment by Msksgm** [comment]
該当 PR がマージされるまで放置
