### ISSUE TITLE
UseCase 層のリファクタリング

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#250]
## 概要

UseCase 層の書き方が統一されていないため、統一する。

## 基本方針

全てのロジックをネストさせていたが、ネストしないようにする。

**Comment by Msksgm** [comment]
## 対象

- article
- comment
- favorite
- profile
- user_and_authentication

**Comment by sunakan** [comment]
都度やっていきますのでcloseします
