### ISSUE TITLE
OpenAPI Generator で生成した API Doc に情報が欠落している気がする

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#266]
## 概要

OpenAPI Generator で生成した API Doc で情報が欠落している気がする。

## サンプル

レスポンスのスキーマが表示されない。

![_Users_sugimotomasaki_work_space_kotlin_realworld-kotlin-springboot-jdbc_build_openapi_doc_index html](https://user-images.githubusercontent.com/49427230/197296201-403fec25-d713-42db-963c-95192979de20.png)

**Comment by Msksgm** [comment]
## 書き出す形式について調査

https://openapi-generator.tech/docs/generators#documentation-generators

より

[asciidoc](https://openapi-generator.tech/docs/generators/asciidoc)
[cwiki](https://openapi-generator.tech/docs/generators/cwiki)
[dynamic-html](https://openapi-generator.tech/docs/generators/dynamic-html)
[html](https://openapi-generator.tech/docs/generators/html)
[html2](https://openapi-generator.tech/docs/generators/html2)
[markdown (beta)](https://openapi-generator.tech/docs/generators/markdown)
[openapi](https://openapi-generator.tech/docs/generators/openapi)
[openapi-yaml](https://openapi-generator.tech/docs/generators/openapi-yaml)
[plantuml (beta)](https://openapi-generator.tech/docs/generators/plantuml)

だった

swgger UI の表示はサポートしていなさそう。
swagger UI の方がみやすい気がするけど、おそらく慣れの問題。
OpenAPI Generator は Swagger Codegen から反発して生まれたものだから、サポートもしなさそう。

**Comment by Msksgm** [comment]
openapi から document を自動生成する自動ツール一覧

https://nordicapis.com/7-open-source-openapi-documentation-generators/

**Comment by Msksgm** [comment]
どうやら定期的に再発するバグっぽい？

https://github.com/OpenAPITools/openapi-generator/issues/3788#issuecomment-1266979202

v6.1.0 にしたらなんか表示された。

![_Users_sugimotomasaki_work_space_kotlin_realworld-kotlin-springboot-jdbc_build_openapi_doc_index html (1)](https://user-images.githubusercontent.com/49427230/197372529-14c651e3-6f4d-45e5-9890-45e29208d139.png)

比較

![localhost_61112_swaggerui html_project=ded9b085 filename=_Users_sugimotomasaki_work_space_kotlin_realworld-kotlin-springboot-jdbc_e2e_openapi yml renderer=0](https://user-images.githubusercontent.com/49427230/197372502-888374a7-1874-419f-9da9-d1018fd97016.png)
/user-images.githubusercontent.com/49427230/197372212-43289be0-c58f-4fbc-b824-ff4bc4be0926.png)

**Comment by Msksgm** [comment]
仮に実運用を想定するのなら、OpenAPI Generator から document を生成するのは、現状の信頼度だと厳しそう。
-> いきなりドキュメントが生成されなくなる可能性があるため。

CLI で生成できないか要調査

**Comment by sunakan** [comment]
バージョンアップする時に、確認事項としてhtml生成して差分取るとかでうまくチェックできますかね？

（自動化を考えましたが、そうすると常にドキュメントをGit管理する必要がありそうでそれはちょっと考えもの）

**Comment by sunakan** [comment]
バグだった

Swagger UIを使おう
