### ISSUE TITLE
komapper の sandbox test が落ちる

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#279]
# 概要

komapper の sandbox test が落ちます。
具体的には、「User一覧を取得する()」が落ちます。

![_Users_sugimotomasaki_work_space_kotlin_realworld-kotlin-springboot-jdbc_build_reports_tests_fullDev_classes_com example realworldkotlinspringbootjdbc sandbox komapper UserTest html](https://user-images.githubusercontent.com/49427230/198424153-3b632a4a-0a1f-4abc-b637-34be24cded15.png)

**Comment by sunakan** [comment]
なんと！すみません 🙇

**Comment by Msksgm** [comment]
解決されたのでクローズします。
