### ISSUE TITLE
TableDrivenTest/ParameterizedTest がしたい

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#31]
## ゴール

- [ ] TableDrivenTestの雛型を作成できる
- [ ] ParameterizedTestの雛型を作成できる

**Comment by Msksgm** [comment]
TableDrivenTest で テスト名がでるのは個人的には must にしたいですね。
コンソールに表示されなくても、junit のレポートに表示させたいので、`UserAndAuthenticationControllerTest$ユーザー登録` のやり方でやりたいです。

**Comment by sunakan** [comment]
TableDrivenTestとして決定したので閉じます
