### ISSUE TITLE
DB周りのテストをもっとスマートに記述したい

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#32]
## ゴール

- [ ] DB周りのテスティングツールの選定
- [ ] 選定したテスティングツールのsandbox testを記述

**Comment by Msksgm** [comment]
そういえば。SQL ファイルを用意して、実行時に読み込みとかできないんですかね？
さすがにすべて jdbc に書いていたらソースコード量に限界があるきが。。。

**Comment by sunakan** [comment]
できるはずです

テスティングツール探す前にそっちからやりますかー

一応現段階で、テスティングツールで考える候補は以下の2つですー

- DBUnit
- DBRider

**Comment by sunakan** [comment]
ちょっとDBRiderはDBUnitを拡張？したっぽいやつなので、薄そうなDBUnitで調べていきます

**Comment by sunakan** [comment]
DBUnitでSQLとかCSVで用意するなら、自前でサクッとやったほうがいい気もしてきました。。。

**Comment by sunakan** [comment]
できれば、、コメントが入れられて、網羅性の視認性があるやつがいいな。。

CSVだと特にコメントが難しそう。。yamlでそれは実現可能そうだけど

**Comment by sunakan** [comment]
a-dbunitだと@Test毎での指定が難しいかもしれないのか

**Comment by sunakan** [comment]
https://www.m3tech.blog/entry/2021/12/19/120000

> （当然、Database Rider使わなくてもパッケージやクラスの切り方、テスト設計で清潔な状態を保つことはできるはずですが、Database RIderはテストメソッド単位で使用するデータファイルを指定できるため、不用意にデータが共有されにくくなるように感じました）。

**Comment by sunakan** [comment]
https://qiita.com/kaburankattara/items/ba738eae9905d51d2b88

```java
    @Test
    @DatabaseSetup("/dbunit/sampleData.xml")
    void HelloWorldが取得されることを確認() {
        String result = helloWorldService.getString();
        assertThat(result).isEqualTo("HelloWorld");
    }
```

とか見るとできそう

**Comment by sunakan** [comment]
DBRiderのドキュメントが見やすくていい気がするけど、相談します

**Comment by sunakan** [comment]
素敵なのは、before/afterを別ファイルで定義してそれを比較できるってのがとてもとても素敵

**Comment by sunakan** [comment]
DBRiderとして合意得られたので、閉じます
