### ISSUE TITLE
Left/Right、Valid/Invalidの順番を統一したい

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#33]
## ゴール

- [x] 決める
- [ ] 洗い出してissue化

**Comment by Msksgm** [comment]
自分は感覚的に、Left -> Right にかきたいので、異常系 -> 正常系 の順番に合わせて、Invalid -> Valid にしたいですね。

**Comment by sunakan** [comment]
NG系が先で合意

**Comment by sunakan** [comment]
洗い出すのはまた別でしようと思うので閉じます
