### ISSUE TITLE
表記ゆれを統一する

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#35]
## ゴール

- [ ] linterを選定
- [ ] linterの使い方学習
- [ ] ciに導入

**Comment by sunakan** [comment]
textlintで良さそうだけど、どこのやつを参考・採用するかはまだ

https://zenn.dev/kgsi/articles/a88273d293abe07c5acb

**Comment by Msksgm** [comment]
textlint って .kt ファイル相手にも使えるんですかね？

**Comment by sunakan** [comment]
issue掃除のため
一旦閉じます
