### ISSUE TITLE
GitHub Actionsでコンパイル時にPermission deniedが出る

### ISSUE THREAD

**Issue by sunakan** [sunakan/realworld-kotlin-springboot-jdbc#48]
## 問題・課題・現象/Issue

```
$ make test
```

- localではうまくいく
- GitHub Actionsが通らない

GitHubActionsでのエラー例

https://github.com/sunakan/realworld-kotlin-springboot-jdbc/runs/7262040747?check_suite_focus=true

```
...
> Task :compileTestKotlin FAILED
e: error while writing /home/runner/work/realworld-kotlin-springboot-jdbc/realworld-kotlin-springboot-jdbc/build/classes/kotlin/test/com/example/realworldkotlinspringbootjdbc/presentation/CommentControllerTest$List(コメント取得) JWT 認証失敗 or 未ログイン$JWT 認証失敗 or 未ログイン-コメント取得-UseCase が「バリデーションエラー」を返す場合、404 エラーレスポンスを返す$mockError$1.class (Permission denied)
...
```

## 調査結果/Report

```kt
val 〇〇 = object : Hoge {}
```

で、〇〇が特定の文字列の時に出るっぽい。。（セキュリティ対策なのかは不明）

## 根本原因/Fundamental cause

不明

## 根本対応/Fundamental solution 

不明

## 暫定対応/Temporary solution idea

- 変数名を変える
or
- 変数に格納しない（直接代入する）

## 対応例/Example

- https://github.com/sunakan/realworld-kotlin-springboot-jdbc/commit/793a6e604d5e9b87c4b54fb165ec5d8f45f0f318

**Comment by Msksgm** [comment]
根本解決ではないですが、自分は Table Driven Test で変数名の統一（エラーにならない変数のみ使わせる）ことで解決できていますね。

**Comment by Msksgm** [comment]
困らなくなったのでクローズ
