### ISSUE TITLE
Profies テーブルいらない説

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#50]
理由

- Profile オブジェクトが OtherUser オブジェクトになったため、データモデル的にも Users テーブルと分離する必要がなくなった。
- 何かしらで user 情報（me、other、profile 問わず）を取得するときには、profiles テーブルが必要なので毎回 JOIN する必要がある
- Users テーブルと Profileテーブルが 1対1 の関係

懸念

- 神 user テーブルを助長する

**Comment by sunakan** [comment]
あ、それはあえてだったりします

JOINが必要にしたり、 `@Transactional` とかを無理やり考えないといけないようにするためにわざと分割してあります

UIが提供する情報とテーブルの構成が１：１になりにくいようわざと分割しました（User情報取得時に）

**Comment by Msksgm** [comment]
承知しました。クローズします。
