### ISSUE TITLE
Slack に PR と issue の通知をしたい

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#75]
このリポジトリのオーナーは msksgm じゃないので、sunakan さんが、以下を realworld-kotlin-通知 で実行する必要がある。
チャンネルを作成したのは、DMだと GitHub アプリが使えなかったため。

```
/github subscribe sunakan/realworld-kotlin-springboot-jdbc pulls,issues
```

**Comment by sunakan** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/43210698/179535184-6c690727-e497-422d-ab7b-2f42f9353172.png">
