### ISSUE TITLE
Repository の役割について考える

### ISSUE THREAD

**Issue by Msksgm** [sunakan/realworld-kotlin-springboot-jdbc#78]
[ドメイン駆動設計 モデリング/実装ガイド](https://booth.pm/ja/items/1835632) を引用すると以下。

> リポジトリは「集約単位で永続化層へのアクセスを提供するもの」です。集約単位で、 という制約を付けている理由は、「第 3 章 3.1 集約」で述べたとおり強い整合性が求めら れるオブジェクトについて、ひとまとまりで整合性を確実に保証するためです。
集約のオブジェクトの親となるオブジェクトを集約ごとに 1 つ決め、そのオブジェクト を「集約ルート」と呼びます。リポジトリは集約ごとに 1 つだけであり、リポジトリに渡 すもの、リポジトリから返されるものは必ず集約ルートのエンティティになり、その他の 子オブジェクトは集約ルートがインスタンス参照した状態で常に扱います。リポジトリか ら子オブジェクトを直接返したり、子オブジェクト用のリポジトリを別途定義したりはし てはいけません。
なお、「第 5 章 アーキテクチャ」のオニオンアーキテクチャの節で説明した通り、リポ ジトリはインターフェイスがドメイン層、その実装クラスがインフラ層になります。これにより、ドメイン層は永続化手段(DB の種類やテーブル構造、OR マッパーなど)に関 して一切知識を持たなくなり、純粋にドメイン知識だけに集中できるようになります。
設計上のポイントは「リポジトリは List のように扱う」ということです。ユーザーク ラスの List があった時、その List は「ユーザー登録する」「ユーザーを退会状態にする」 というメソッドは持たないはずです。新規登録状態のユーザー、退会状態のユーザーを add するという使い方をするでしょう。リポジトリも同じです。List に持たせないような メソッド、つまりドメイン知識 (ルール/制約) を持っていたとしたら、それは責務過剰な のでリポジトリから別のクラスに委譲しましょう。
 この方針は、テスト時にも役立ちます。リポジトリが永続化層へのアクセスのみを提供していれば、テスト時にはリポジトリの実装クラスをオンメモリのモック実装に差し替えることが容易になります。この際、リポジトリがドメイン知識を実装していると、その部分のロジックをモック内で再度実装することになり、テスト内容が正しく保証されなくなるリスクが生まれます。

- 集約単位で永続化層へのアクセスを提供するもの
- リポジトリはインターフェースがドメイン層、実装クラスがインフラ層
- リポジトリは List のように扱う

**Comment by Msksgm** [comment]
## 集約単位で永続化層へのアクセスを提供する

集約の例、Comment、Article、OtherUser。

Q. Comment をDBから取得するとき、OtherUser（userId、usernameなど）を持ってきていいか
A. NG


Q. Comment を DB から取得するとき、slug を渡して Comment に該当する Article が存在するか確認していいか
A. 多分 NG？

**Comment by Msksgm** [comment]
## リポジトリはインターフェースがドメイン層、実装クラスがインフラ層

特になし

**Comment by Msksgm** [comment]
## リポジトリは List のように扱う

違和感を感じる書き方。slug によって、article が一意に定まることを知っているから？

```kotlin
val comments = commentRepository.list(slug)
```


おそらく自然な書き方。comment は articleId にぶら下がっているから？

```kotlin
val articleId = articleRepository.get(slug)
val comments = commentRepository.list(articleId)
```

**Comment by sunakan** [comment]
もしかして CreatedArticle の 識別子は ArticleIdではなくSlugにすると全部うまく行きそう？

根拠１：Slugもユニーク属性である
根拠２：UIに引っ張られるが、PUTによるArticle更新時、Slugを指定していている
根拠３：UIに引っ張られるが、ArticleのResponseデータとして、SlugはあってもArticleIDらしきものがない

**Comment by Msksgm** [comment]
ようはバランスおじさんだった。

https://peing.net/ja/q/c7a67cf4-68be-4184-a95c-f4938c69ac4e

どっちにバランスをよせるかなんだと思う
前者のほうがフラットになるし、後者のほうが正しさを担保できる。

- UseCase に確認の責務を持たせる
- Repository に確認の責務を持たせる

一旦クローズ
